### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by athkalia** [ajitsing/Sherlock#2]
Hello,

this is an interesting library, thanks for sharing! Unfortunately including Realm will be prohibitive for quite a few devs cause of its size. Also, enabling databinding just for the sake of including this library in a commercial project would be very difficult to justify.

Libraries should minimize dependencies like that to make it easier for developers to integrate them into projects. I would suggest rewriting it without these 2 components.

Cheers,
Sakis

**Comment by ajitsing** [comment]
Thanks for the suggestions, will consider it for the next version.

**Comment by athkalia** [comment]
Cool, give me a shout if possible I'd be very interested in using your library in that case

**Comment by ajitsing** [comment]
@athkalia Released [Sherlock-1.0.1](https://github.com/ajitsing/Sherlock/releases/tag/1.0.1) to address the above issues.
