### ISSUE TITLE
Add no-op dependency for release build type

### ISSUE THREAD

**Issue by athkalia** [ajitsing/Sherlock#3]
Hello,

It's a usual practice for libraries like this (that only exist for debug builds) to release a no-op version of the library that is completely empty, so that users of the library can use it in their app without worrying that the library is going to increase their release APK size, or cause any side effects in production. For an example see here: https://github.com/square/leakcanary

This can be fixed on the developers side by using an interface (for example see https://github.com/athkalia/Just-Another-Android-App/blob/8a5c677b2b0d0f2dcc123d40b770307a13786b64/app/src/main/java/com/example/tools/stetho/StethoTool.java in my project for introducing stetho only for debug builds), but it's much more convenient when fixed by the library

**Comment by ajitsing** [comment]
Hi @athkalia 
Thanks again for the suggestion. I like the idea of having no-op implementation. Will be releasing it soon.

**Comment by ajitsing** [comment]
@athkalia  @rubengees Released Sherlock [1.0.2](https://github.com/ajitsing/Sherlock/releases/tag/1.0.2)

**Comment by athkalia** [comment]
damn man, you are fast!
