### ISSUE TITLE
CrashListActivity does not exist when use sherlock-no-op on release

### ISSUE THREAD

**Issue by af-kabramov** [ajitsing/Sherlock#5]
com.singhajit.sherlock.crashes.activity does not exist
import com.singhajit.sherlock.crashes.activity.CrashListActivity;
                                              ^
1 error

does not exists when use releaseCompile('com.github.ajitsing:sherlock-no-op:1.0.2@aar')

maybe you can provide method Sherlock.openCrashListActivity(context); ?

**Comment by ajitsing** [comment]
@af-kabramov thanks for reporting this, will fix it ASAP.

**Comment by af-kabramov** [comment]
@ajitsing also it is not related t this bug, but in CrashAnalyzer you can use Log.getStackTraceString(throwable) to get errorStackTraceString

**Comment by af-kabramov** [comment]
also
public class Crash {
}
no stub getters... etc

**Comment by ajitsing** [comment]
@af-kabramov this is fixed as part of https://github.com/ajitsing/Sherlock/commit/9546d5ef26aee51091e4b46c1f9c12f8248b61bb
