### ISSUE TITLE
Theming 

### ISSUE THREAD

**Issue by rgocal** [ajitsing/Sherlock#8]
Is their a way to theme the list activity? 

_Sent from my Mi 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ajitsing** [comment]
Hi @rgocal 

Currently `CrashListActivity` uses `@style/SherlockTheme`. If you wish to have your own theme then you can override the default Sherlock theme in your app. Here is a [link](https://stackoverflow.com/questions/35315120/how-to-override-styles-of-a-library-which-has-its-own-activity) to help you :)

Let me know if you have any other question.

**Comment by rgocal** [comment]
Oh awesome, Never gave that a thought. Using this in my launcher and theme of the activity was stressing me out
