### ISSUE TITLE
CrashListActivity not opening on Android O

### ISSUE THREAD

**Issue by rgocal** [ajitsing/Sherlock#9]
So I updated the SDK to 26 in my launcher app and a crash accurs telling me the activity does not exist and if I implemented it in my Manifest. So I thought about it and made a new activity that extends CrashListActivity and it opens but nothing shows. Notifications do not appear either to indicate crash. whats happening...

**Comment by ajitsing** [comment]
@rgocal Thanks for reporting this issue, will fix it ASAP.

The problem is Android O needs a notification channel to show the notification. Go through this [link](https://stackoverflow.com/questions/43093260/notification-not-showing-in-android-8-oreo) for more details.

**Comment by ajitsing** [comment]
Regarding CrashListActivity not showing any crashes, its not happening in my case, I am able to see all the crashes.

<img width="343" alt="screen shot 2017-09-10 at 12 19 51" src="https://user-images.githubusercontent.com/3875127/30246835-8a3e9b68-9622-11e7-808f-896388973f07.png">

**Comment by rgocal** [comment]
Can you click on them?

**Comment by ajitsing** [comment]
It works just fine. Also I have fixed the notification issue in https://github.com/ajitsing/Sherlock/commit/034606e39da7c9fcf2663dd07a2d295c8014cf66

Will be releasing 1.0.4 soon!

**Comment by rgocal** [comment]
Thank you, i really depend on this for my users.

**Comment by ajitsing** [comment]
Released Sherlock [1.0.4](https://github.com/ajitsing/Sherlock/releases/tag/1.0.4)
